### ISSUE TITLE
arp.sniff reporting error

### ISSUE THREAD

**Issue by JokeNeverSoke** [portantier/habu#20]
Running habu.sniff.arp on Mac OS X produces the following error:

$ habu.arp.sniff
Waiting for ARP packets...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/habu.arp.sniff", line 10, in <module>
    sys.exit(cmd_arp_sniff())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/habu/cli/cmd_arp_sniff.py", line 61, in cmd_arp_sniff
    sniff(filter="arp", store=False, prn=procpkt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scapy/sendrecv.py", line 886, in sniff
    r = prn(p)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/habu/cli/cmd_arp_sniff.py", line 24, in procpkt
    hosts[pkt[ARP].psrc]['vendor'] = conf.manufdb._get_manuf(pkt[ARP].hwsrc)
AttributeError: 'NoneType' object has no attribute '_get_manuf'

**Comment by fportantier** [comment]
Seems like you don't have the manufdb. I don't know why, but we can use a try block and set the manufacturer to "unknown".

**Comment by fportantier** [comment]
Please, check using the latest version that includes the changes for check if manufdb is available
