### ISSUE TITLE
README.md missing on pypi, setup fails

### ISSUE THREAD

**Issue by mmguero** [portantier/habu#5]
In the last two or three days:

```
$ pip3 install habu
Collecting habu
  Downloading https://files.pythonhosted.org/packages/c1/a5/db298f9b1e094167c39a39015336834c13482d05a97577770ce8cc539ab0/habu-0.0.72.tar.gz (731kB)
    100% |████████████████████████████████| 737kB 16.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qahj4zof/habu/setup.py", line 3, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qahj4zof/habu/
```

I downloaded and unpacked habu-0.0.72.tar.gz manually, and sure enough, README.md isn't in there.

**Comment by fportantier** [comment]
You're right! 

The python package for the last version (0.0.72) has been generated with an error. (my fault).

I've uploaded the new version (0.0.73) that fixes the problem.

Thanks for the report! And please, tell me if you find any other error.

Regards,
