### ISSUE TITLE
Blackarch dependency version issue prompt_toolkit==1.0.15

### ISSUE THREAD

**Issue by Str-Gen** [portantier/habu#7]
I've installed Habu on Arch Linux, through the BlackArch repo.
However, none of the dependencies get picked up during the installation and even after installing them manually one issue remains. The version of prompt_toolkit is somehow locked to 1.0.15. Without virtualenv Arch linux does not support version locking like this. 

Is there a reason to stick to this specific version and if not, what should I modify to just use the latest version of prompt_toolkit?

```

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 2.0.7 (/usr/lib/python3.7/site-packages), Requirement.parse('prompt_toolkit==1.0.15'), {'habu'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/habu.arp.poison", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prompt_toolkit==1.0.15' distribution was not found and is required by habu
```

**Comment by Str-Gen** [comment]
A potential solution is editing /usr/lib/python3.7/site-packages/habu-VERSION-py3.7.egg-info/requires.txt, removing the ==1.0.15 on the line containing prompt_toolkit. 
Based on testing some of habu's commands, this does not break the application. Please consider removing the version lock in future versions.

**Comment by fportantier** [comment]
Yes, you're right, prompt toolkit is only used on habu.jshell.
I've removed has a dependency in version 1.0.2
We need a way to put a list of recommended packages.
I will research on that.
Thanks!
